name: Laravel Migration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-migration:

    runs-on: ubuntu-latest

    steps:
    - name: Run the database migration
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: mealplanner
        DB_HOST: mealplanner.c9ttvnc4ekpj.us-east-1.rds.amazonaws.com
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
      run: php artisan migrate
