name: Laravel Migration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DB_DATABASE: mealplanner-db
  DB_PASSWORD: mealplannerdb
  DB_PORT: 3306
  DB_USERNAME: admin
  DB_HOST: mealplanner-db.coixkocj2bcb.us-east-1.rds.amazonaws.com

jobs:
  laravel-migration:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: DB host
      run: echo "${{env.DB_HOST}}"
    - name: DB Database
      run: echo "${{env.DB_DATABASE}}"
    - name: DB Username
      run: echo "${{env.DB_USERNAME}}"
    - name: Configure environment
      run: |
        echo "DB_HOST=${{ env.DB_HOST }}" >> .env
        echo "DB_DATABASE=${{ env.DB_DATABASE }}" >> .env
        echo "DB_USERNAME=${{ env.DB_USERNAME }}" >> .env
        echo "DB_PASSWORD=${{ env.DB_PASSWORD }}" >> .env
    - name: Generate key
      run: php artisan key:generate
    - name: Run migrations
      run: |
        php artisan migrate --force

